name = "lapce-prisma"
version = "0.1.0"
author = "tingfeng-key"
display-name = "prisma"
description = "prisma plugin for lapce"
wasm = "lapce-prisma.wasm"

[activation]
language = ["prisma"]
workspace-contains = ["*/*.prisma"]

[config."volt.serverPath"]
default = ""
description = "Path to prisma LSP executable"
