author = "tingfeng-key"
description = "Prisma plugin for lapce"
display-name = "Prisma"
icon = "logo.png"
name = "lapce-prisma"
repository = "https://github.com/tingfeng-key/lapce-prisma"
version = "0.1.0"
wasm = "bin/lapce-prisma.wasm"

[activation]
language = ["prisma"]
workspace-contains = ["*/*.prisma"]

[config."volt.serverPath"]
default = ""
description = "Path to prisma LSP executable"
