author = "tingfeng-key"
description = "Svelte plugin for lapce"
display-name = "Svelte"
icon = "logo.png"
name = "lapce-svelte"
repository = "https://github.com/brocococonut/lapce-svelte"
version = "0.1.0"
wasm = "bin/lapce-svelte.wasm"

[activation]
language = ["svelte"]
workspace-contains = ["*/*.svelte"]

[config."volt.serverPath"]
default = ""
description = "Path to svelte LSP executable"
